name = "ParSitter"
uuid = "bdeffda0-9f75-4d6c-9dad-1bfd8db84b8f"
authors = ["Corneliu Cofaru <cornel@oxoaresearch.com>"]
version = "0.1.0"

[deps]
ArgParse = "c7e460c6-2fb9-53a9-8c5b-16f535851c63"
JSON = "682c06a0-de6a-54ab-a142-c8b1cf79cde6"

[compat]
ArgParse = "1.2.0"
JSON = "0.21.4"
